///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String imagesForgetPassword = 'assets/images/forgetPassword.png';
  static const String imagesOnBoarding1 = 'assets/images/onBoarding1.png';
  static const String imagesOnBoarding2 = 'assets/images/onBoarding2.png';
  static const String imagesOnBoarding3 = 'assets/images/onBoarding3.png';
  static const String imagesSuccessOrder = 'assets/images/SuccessOrder.png';
  static const String imagesVector1 = 'assets/images/Vector1.svg';
  static const String imagesVector2 = 'assets/images/Vector2.svg';

}
